
ARCH := cortex_m3
TOOL := gnu

INCLUDES = -Iapplication/inc
INCLUDES += -Ilib/Azure/threadx/common/inc -Ilib/Azure/threadx/ports/$(ARCH)/$(TOOL)/inc
INCLUDES += -Ilib/Azure/guix/ports/$(ARCH)/$(TOOL)/inc -Ilib/Azure/guix/common/inc
INCLUDES += -Ilib/$(LPC_DIR)/inc

#CFLAGS += -Wa,-adhln -g

obj-y = src/

export cmd_file := application/gcc_arm.ld