ARCH := cortex_m3
TOOL := gnu

obj-y += common/src/

INCLUDES = -I$(AZURE_DIR)/guix/common/inc -I$(AZURE_DIR)/guix/ports/$(ARCH)/$(TOOL)/inc
INCLUDES += -I$(AZURE_DIR)/threadx/common/inc -I$(AZURE_DIR)/threadx/ports/$(ARCH)/$(TOOL)/inc
